[book]
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
multilingual = false
src = "src"
title = "BcnRust"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/BcnRust/bcnrust.github.io"
